/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as assetDefinitions_index from "../assetDefinitions/index.js";
import type * as assetDefinitions_web_mutations_addAsset from "../assetDefinitions/web/mutations/addAsset.js";
import type * as assetDefinitions_web_mutations_assignAssetToUser from "../assetDefinitions/web/mutations/assignAssetToUser.js";
import type * as assetDefinitions_web_mutations_bulkUpdateAssets from "../assetDefinitions/web/mutations/bulkUpdateAssets.js";
import type * as assetDefinitions_web_mutations_checkInAsset from "../assetDefinitions/web/mutations/checkInAsset.js";
import type * as assetDefinitions_web_mutations_checkOutAsset from "../assetDefinitions/web/mutations/checkOutAsset.js";
import type * as assetDefinitions_web_mutations_completeMaintenance from "../assetDefinitions/web/mutations/completeMaintenance.js";
import type * as assetDefinitions_web_mutations_editAssetDetails from "../assetDefinitions/web/mutations/editAssetDetails.js";
import type * as assetDefinitions_web_mutations_generateAssetBarcode from "../assetDefinitions/web/mutations/generateAssetBarcode.js";
import type * as assetDefinitions_web_mutations_performAssetAudit from "../assetDefinitions/web/mutations/performAssetAudit.js";
import type * as assetDefinitions_web_mutations_reactivateAsset from "../assetDefinitions/web/mutations/reactivateAsset.js";
import type * as assetDefinitions_web_mutations_reorderSupplies from "../assetDefinitions/web/mutations/reorderSupplies.js";
import type * as assetDefinitions_web_mutations_retireAsset from "../assetDefinitions/web/mutations/retireAsset.js";
import type * as assetDefinitions_web_mutations_scheduleMaintenance from "../assetDefinitions/web/mutations/scheduleMaintenance.js";
import type * as assetDefinitions_web_mutations_transferAsset from "../assetDefinitions/web/mutations/transferAsset.js";
import type * as assetDefinitions_web_mutations_unassignAssetFromUser from "../assetDefinitions/web/mutations/unassignAssetFromUser.js";
import type * as assetDefinitions_web_mutations_updateAssetStatus from "../assetDefinitions/web/mutations/updateAssetStatus.js";
import type * as assetDefinitions_web_queries_getAssetAlerts from "../assetDefinitions/web/queries/getAssetAlerts.js";
import type * as assetDefinitions_web_queries_getAssetAnalytics from "../assetDefinitions/web/queries/getAssetAnalytics.js";
import type * as assetDefinitions_web_queries_getAssetById from "../assetDefinitions/web/queries/getAssetById.js";
import type * as assetDefinitions_web_queries_getAssetDashboardData from "../assetDefinitions/web/queries/getAssetDashboardData.js";
import type * as assetDefinitions_web_queries_getAssetHistory from "../assetDefinitions/web/queries/getAssetHistory.js";
import type * as assetDefinitions_web_queries_getAssetReports from "../assetDefinitions/web/queries/getAssetReports.js";
import type * as assetDefinitions_web_queries_getAssetUtilization from "../assetDefinitions/web/queries/getAssetUtilization.js";
import type * as assetDefinitions_web_queries_getAssets from "../assetDefinitions/web/queries/getAssets.js";
import type * as assetDefinitions_web_queries_getInventoryLevels from "../assetDefinitions/web/queries/getInventoryLevels.js";
import type * as assetDefinitions_web_queries_getMaintenanceSchedule from "../assetDefinitions/web/queries/getMaintenanceSchedule.js";
import type * as assetDefinitions_web_queries_getManagerProperties from "../assetDefinitions/web/queries/getManagerProperties.js";
import type * as assets from "../assets.js";
import type * as http from "../http.js";
import type * as maintenance from "../maintenance.js";
import type * as maintenanceDefinitions_index from "../maintenanceDefinitions/index.js";
import type * as maintenanceDefinitions_mobile_index from "../maintenanceDefinitions/mobile/index.js";
import type * as maintenanceDefinitions_mobile_mutations_cancelRequest from "../maintenanceDefinitions/mobile/mutations/cancelRequest.js";
import type * as maintenanceDefinitions_mobile_mutations_createRequest from "../maintenanceDefinitions/mobile/mutations/createRequest.js";
import type * as maintenanceDefinitions_mobile_mutations_deleteRequest from "../maintenanceDefinitions/mobile/mutations/deleteRequest.js";
import type * as maintenanceDefinitions_mobile_mutations_index from "../maintenanceDefinitions/mobile/mutations/index.js";
import type * as maintenanceDefinitions_mobile_mutations_tenantConfirmCompletion from "../maintenanceDefinitions/mobile/mutations/tenantConfirmCompletion.js";
import type * as maintenanceDefinitions_mobile_mutations_updateRequest from "../maintenanceDefinitions/mobile/mutations/updateRequest.js";
import type * as maintenanceDefinitions_mobile_queries_getMyCurrentRequests from "../maintenanceDefinitions/mobile/queries/getMyCurrentRequests.js";
import type * as maintenanceDefinitions_mobile_queries_getRequestStatus from "../maintenanceDefinitions/mobile/queries/getRequestStatus.js";
import type * as maintenanceDefinitions_mobile_queries_getRequests from "../maintenanceDefinitions/mobile/queries/getRequests.js";
import type * as maintenanceDefinitions_mobile_queries_getRequestsById from "../maintenanceDefinitions/mobile/queries/getRequestsById.js";
import type * as maintenanceDefinitions_mobile_queries_index from "../maintenanceDefinitions/mobile/queries/index.js";
import type * as maintenanceDefinitions_web_mutations_assignTechnician from "../maintenanceDefinitions/web/mutations/assignTechnician.js";
import type * as maintenanceDefinitions_web_mutations_bulkUpdateStatus from "../maintenanceDefinitions/web/mutations/bulkUpdateStatus.js";
import type * as maintenanceDefinitions_web_mutations_updateMaintenanceCost from "../maintenanceDefinitions/web/mutations/updateMaintenanceCost.js";
import type * as maintenanceDefinitions_web_mutations_updateMaintenanceStatus from "../maintenanceDefinitions/web/mutations/updateMaintenanceStatus.js";
import type * as maintenanceDefinitions_web_queries_getMaintenanceKPIs from "../maintenanceDefinitions/web/queries/getMaintenanceKPIs.js";
import type * as maintenanceDefinitions_web_queries_getMaintenanceRequests from "../maintenanceDefinitions/web/queries/getMaintenanceRequests.js";
import type * as maintenanceDefinitions_web_queries_getMaintenanceTrends from "../maintenanceDefinitions/web/queries/getMaintenanceTrends.js";
import type * as maintenanceDefinitions_web_queries_getMaintenanceUpdates from "../maintenanceDefinitions/web/queries/getMaintenanceUpdates.js";
import type * as maintenanceDefinitions_web_queries_getMaintenanceUpdatesCount from "../maintenanceDefinitions/web/queries/getMaintenanceUpdatesCount.js";
import type * as maintenanceDefinitions_web_queries_getManagerProperties from "../maintenanceDefinitions/web/queries/getManagerProperties.js";
import type * as maintenanceDefinitions_web_queries_getTechnicianWorkload from "../maintenanceDefinitions/web/queries/getTechnicianWorkload.js";
import type * as maintenanceDefinitions_web_queries_getTechnicians from "../maintenanceDefinitions/web/queries/getTechnicians.js";
import type * as maintenanceDefinitions_web_queries_getUnitsByProperty from "../maintenanceDefinitions/web/queries/getUnitsByProperty.js";
import type * as noticeboard from "../noticeboard.js";
import type * as noticeboardDefinitions_index from "../noticeboardDefinitions/index.js";
import type * as noticeboardDefinitions_mobile_mutations_acknowledgeNotice from "../noticeboardDefinitions/mobile/mutations/acknowledgeNotice.js";
import type * as noticeboardDefinitions_mobile_mutations_addEventToCalendar from "../noticeboardDefinitions/mobile/mutations/addEventToCalendar.js";
import type * as noticeboardDefinitions_mobile_mutations_sendFeedback from "../noticeboardDefinitions/mobile/mutations/sendFeedback.js";
import type * as noticeboardDefinitions_mobile_mutations_submitPollResponse from "../noticeboardDefinitions/mobile/mutations/submitPollResponse.js";
import type * as noticeboardDefinitions_mobile_queries_getActivePolls from "../noticeboardDefinitions/mobile/queries/getActivePolls.js";
import type * as noticeboardDefinitions_mobile_queries_getCommunityNews from "../noticeboardDefinitions/mobile/queries/getCommunityNews.js";
import type * as noticeboardDefinitions_mobile_queries_getEvents from "../noticeboardDefinitions/mobile/queries/getEvents.js";
import type * as noticeboardDefinitions_mobile_queries_getNoticeById from "../noticeboardDefinitions/mobile/queries/getNoticeById.js";
import type * as noticeboardDefinitions_mobile_queries_getNotices from "../noticeboardDefinitions/mobile/queries/getNotices.js";
import type * as noticeboardDefinitions_web_mutations_acknowledgeNotice from "../noticeboardDefinitions/web/mutations/acknowledgeNotice.js";
import type * as noticeboardDefinitions_web_mutations_createNotice from "../noticeboardDefinitions/web/mutations/createNotice.js";
import type * as noticeboardDefinitions_web_mutations_createPoll from "../noticeboardDefinitions/web/mutations/createPoll.js";
import type * as noticeboardDefinitions_web_mutations_deleteNotice from "../noticeboardDefinitions/web/mutations/deleteNotice.js";
import type * as noticeboardDefinitions_web_mutations_deletePoll from "../noticeboardDefinitions/web/mutations/deletePoll.js";
import type * as noticeboardDefinitions_web_mutations_scheduleNotice from "../noticeboardDefinitions/web/mutations/scheduleNotice.js";
import type * as noticeboardDefinitions_web_mutations_sendNoticeToAll from "../noticeboardDefinitions/web/mutations/sendNoticeToAll.js";
import type * as noticeboardDefinitions_web_mutations_sendNoticeToUnit from "../noticeboardDefinitions/web/mutations/sendNoticeToUnit.js";
import type * as noticeboardDefinitions_web_mutations_submitPollResponse from "../noticeboardDefinitions/web/mutations/submitPollResponse.js";
import type * as noticeboardDefinitions_web_mutations_updateNotice from "../noticeboardDefinitions/web/mutations/updateNotice.js";
import type * as noticeboardDefinitions_web_mutations_updatePoll from "../noticeboardDefinitions/web/mutations/updatePoll.js";
import type * as noticeboardDefinitions_web_queries_getAllUnits from "../noticeboardDefinitions/web/queries/getAllUnits.js";
import type * as noticeboardDefinitions_web_queries_getManagerProperties from "../noticeboardDefinitions/web/queries/getManagerProperties.js";
import type * as noticeboardDefinitions_web_queries_getNoticeAcknowledgments from "../noticeboardDefinitions/web/queries/getNoticeAcknowledgments.js";
import type * as noticeboardDefinitions_web_queries_getNoticeById from "../noticeboardDefinitions/web/queries/getNoticeById.js";
import type * as noticeboardDefinitions_web_queries_getNotices from "../noticeboardDefinitions/web/queries/getNotices.js";
import type * as noticeboardDefinitions_web_queries_getNoticesCount from "../noticeboardDefinitions/web/queries/getNoticesCount.js";
import type * as noticeboardDefinitions_web_queries_getPollResponseCounts from "../noticeboardDefinitions/web/queries/getPollResponseCounts.js";
import type * as noticeboardDefinitions_web_queries_getPollStats from "../noticeboardDefinitions/web/queries/getPollStats.js";
import type * as noticeboardDefinitions_web_queries_getPollWithResponses from "../noticeboardDefinitions/web/queries/getPollWithResponses.js";
import type * as noticeboardDefinitions_web_queries_getPollsByProperty from "../noticeboardDefinitions/web/queries/getPollsByProperty.js";
import type * as noticeboardDefinitions_web_queries_getUnitsByProperty from "../noticeboardDefinitions/web/queries/getUnitsByProperty.js";
import type * as property from "../property.js";
import type * as propertyDefinitions_index from "../propertyDefinitions/index.js";
import type * as propertyDefinitions_mobile_index from "../propertyDefinitions/mobile/index.js";
import type * as propertyDefinitions_mobile_queries_getMyProperties from "../propertyDefinitions/mobile/queries/getMyProperties.js";
import type * as propertyDefinitions_mobile_queries_getProperties from "../propertyDefinitions/mobile/queries/getProperties.js";
import type * as propertyDefinitions_mobile_queries_index from "../propertyDefinitions/mobile/queries/index.js";
import type * as propertyDefinitions_web_index from "../propertyDefinitions/web/index.js";
import type * as propertyDefinitions_web_mutations_createProperty from "../propertyDefinitions/web/mutations/createProperty.js";
import type * as propertyDefinitions_web_mutations_index from "../propertyDefinitions/web/mutations/index.js";
import type * as propertyDefinitions_web_queries_getManagerProperties from "../propertyDefinitions/web/queries/getManagerProperties.js";
import type * as propertyDefinitions_web_queries_index from "../propertyDefinitions/web/queries/index.js";
import type * as seeders_assets from "../seeders/assets.js";
import type * as seeders_notice from "../seeders/notice.js";
import type * as seeders_units from "../seeders/units.js";
import type * as seeders_visitorLogs from "../seeders/visitorLogs.js";
import type * as seeders_visitorRequests from "../seeders/visitorRequests.js";
import type * as seeders_watchlist from "../seeders/watchlist.js";
import type * as tech from "../tech.js";
import type * as techDefinitions_mobile_index from "../techDefinitions/mobile/index.js";
import type * as techDefinitions_mobile_mutations_addMaintenancePhoto from "../techDefinitions/mobile/mutations/addMaintenancePhoto.js";
import type * as techDefinitions_mobile_mutations_checkinAsset from "../techDefinitions/mobile/mutations/checkinAsset.js";
import type * as techDefinitions_mobile_mutations_checkoutAsset from "../techDefinitions/mobile/mutations/checkoutAsset.js";
import type * as techDefinitions_mobile_mutations_index from "../techDefinitions/mobile/mutations/index.js";
import type * as techDefinitions_mobile_mutations_reportAssetIssue from "../techDefinitions/mobile/mutations/reportAssetIssue.js";
import type * as techDefinitions_mobile_mutations_requestTenantApproval from "../techDefinitions/mobile/mutations/requestTenantApproval.js";
import type * as techDefinitions_mobile_mutations_scheduleAssetMaintenance from "../techDefinitions/mobile/mutations/scheduleAssetMaintenance.js";
import type * as techDefinitions_mobile_mutations_updateMaintenanceCost from "../techDefinitions/mobile/mutations/updateMaintenanceCost.js";
import type * as techDefinitions_mobile_mutations_updateRequestStatus from "../techDefinitions/mobile/mutations/updateRequestStatus.js";
import type * as techDefinitions_mobile_mutations_uploadMaintenancePhoto from "../techDefinitions/mobile/mutations/uploadMaintenancePhoto.js";
import type * as techDefinitions_mobile_queries_getAssetInventory from "../techDefinitions/mobile/queries/getAssetInventory.js";
import type * as techDefinitions_mobile_queries_getAssignedRequests from "../techDefinitions/mobile/queries/getAssignedRequests.js";
import type * as techDefinitions_mobile_queries_getAvailableAssets from "../techDefinitions/mobile/queries/getAvailableAssets.js";
import type * as techDefinitions_mobile_queries_getCheckedOutAssets from "../techDefinitions/mobile/queries/getCheckedOutAssets.js";
import type * as techDefinitions_mobile_queries_getMaintenanceDashboard from "../techDefinitions/mobile/queries/getMaintenanceDashboard.js";
import type * as techDefinitions_mobile_queries_getRequestDetails from "../techDefinitions/mobile/queries/getRequestDetails.js";
import type * as techDefinitions_mobile_queries_index from "../techDefinitions/mobile/queries/index.js";
import type * as unit from "../unit.js";
import type * as unitDefinitions_index from "../unitDefinitions/index.js";
import type * as unitDefinitions_mobile_index from "../unitDefinitions/mobile/index.js";
import type * as unitDefinitions_mobile_mutations_assignTenantToUnit from "../unitDefinitions/mobile/mutations/assignTenantToUnit.js";
import type * as unitDefinitions_mobile_mutations_createAndAssignUnit from "../unitDefinitions/mobile/mutations/createAndAssignUnit.js";
import type * as unitDefinitions_mobile_mutations_createUnit from "../unitDefinitions/mobile/mutations/createUnit.js";
import type * as unitDefinitions_mobile_mutations_index from "../unitDefinitions/mobile/mutations/index.js";
import type * as unitDefinitions_mobile_mutations_updateUnit from "../unitDefinitions/mobile/mutations/updateUnit.js";
import type * as unitDefinitions_mobile_queries_getMyUnits from "../unitDefinitions/mobile/queries/getMyUnits.js";
import type * as unitDefinitions_mobile_queries_getUnitDetails from "../unitDefinitions/mobile/queries/getUnitDetails.js";
import type * as unitDefinitions_mobile_queries_getUnitsByProperty from "../unitDefinitions/mobile/queries/getUnitsByProperty.js";
import type * as unitDefinitions_mobile_queries_index from "../unitDefinitions/mobile/queries/index.js";
import type * as user from "../user.js";
import type * as userDefinitions_index from "../userDefinitions/index.js";
import type * as userDefinitions_mobile_index from "../userDefinitions/mobile/index.js";
import type * as userDefinitions_mobile_queries_getCurrentUser from "../userDefinitions/mobile/queries/getCurrentUser.js";
import type * as userDefinitions_mobile_queries_index from "../userDefinitions/mobile/queries/index.js";
import type * as userDefinitions_web_index from "../userDefinitions/web/index.js";
import type * as userDefinitions_web_queries_getCurrentUser from "../userDefinitions/web/queries/getCurrentUser.js";
import type * as userDefinitions_web_queries_getUserById from "../userDefinitions/web/queries/getUserById.js";
import type * as userDefinitions_web_queries_getUsers from "../userDefinitions/web/queries/getUsers.js";
import type * as visitorLog from "../visitorLog.js";
import type * as visitorLogDefinitions_index from "../visitorLogDefinitions/index.js";
import type * as visitorLogDefinitions_web_mutations_checkInVisitor from "../visitorLogDefinitions/web/mutations/checkInVisitor.js";
import type * as visitorLogDefinitions_web_mutations_checkOutVisitor from "../visitorLogDefinitions/web/mutations/checkOutVisitor.js";
import type * as visitorLogDefinitions_web_mutations_index from "../visitorLogDefinitions/web/mutations/index.js";
import type * as visitorLogDefinitions_web_mutations_markVisitorNoShow from "../visitorLogDefinitions/web/mutations/markVisitorNoShow.js";
import type * as visitorLogDefinitions_web_queries_getVisitorLog from "../visitorLogDefinitions/web/queries/getVisitorLog.js";
import type * as visitorLogDefinitions_web_queries_index from "../visitorLogDefinitions/web/queries/index.js";
import type * as visitorRequest from "../visitorRequest.js";
import type * as visitorRequestDefinitions_index from "../visitorRequestDefinitions/index.js";
import type * as visitorRequestDefinitions_web_mutations_approveVisitorRequest from "../visitorRequestDefinitions/web/mutations/approveVisitorRequest.js";
import type * as visitorRequestDefinitions_web_mutations_createVisitorEntry from "../visitorRequestDefinitions/web/mutations/createVisitorEntry.js";
import type * as visitorRequestDefinitions_web_mutations_denyVisitorRequest from "../visitorRequestDefinitions/web/mutations/denyVisitorRequest.js";
import type * as visitorRequestDefinitions_web_mutations_generateVisitorBadge from "../visitorRequestDefinitions/web/mutations/generateVisitorBadge.js";
import type * as visitorRequestDefinitions_web_mutations_index from "../visitorRequestDefinitions/web/mutations/index.js";
import type * as visitorRequestDefinitions_web_queries_exportVisitorReports from "../visitorRequestDefinitions/web/queries/exportVisitorReports.js";
import type * as visitorRequestDefinitions_web_queries_getActiveVisitors from "../visitorRequestDefinitions/web/queries/getActiveVisitors.js";
import type * as visitorRequestDefinitions_web_queries_index from "../visitorRequestDefinitions/web/queries/index.js";
import type * as visitorRequestDefinitions_web_queries_searchVisitorHistory from "../visitorRequestDefinitions/web/queries/searchVisitorHistory.js";
import type * as watchList from "../watchList.js";
import type * as watchListDefinitions_index from "../watchListDefinitions/index.js";
import type * as watchListDefinitions_web_mutations_manageWatchlist from "../watchListDefinitions/web/mutations/manageWatchlist.js";
import type * as webhook from "../webhook.js";
import type * as webhookDefinitions_handleUserCreated from "../webhookDefinitions/handleUserCreated.js";
import type * as webhookDefinitions_handleUserDeleted from "../webhookDefinitions/handleUserDeleted.js";
import type * as webhookDefinitions_handleUserUpdated from "../webhookDefinitions/handleUserUpdated.js";
import type * as webhookDefinitions_index from "../webhookDefinitions/index.js";
import type * as webhookDefinitions_verifyWebhook from "../webhookDefinitions/verifyWebhook.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  "assetDefinitions/index": typeof assetDefinitions_index;
  "assetDefinitions/web/mutations/addAsset": typeof assetDefinitions_web_mutations_addAsset;
  "assetDefinitions/web/mutations/assignAssetToUser": typeof assetDefinitions_web_mutations_assignAssetToUser;
  "assetDefinitions/web/mutations/bulkUpdateAssets": typeof assetDefinitions_web_mutations_bulkUpdateAssets;
  "assetDefinitions/web/mutations/checkInAsset": typeof assetDefinitions_web_mutations_checkInAsset;
  "assetDefinitions/web/mutations/checkOutAsset": typeof assetDefinitions_web_mutations_checkOutAsset;
  "assetDefinitions/web/mutations/completeMaintenance": typeof assetDefinitions_web_mutations_completeMaintenance;
  "assetDefinitions/web/mutations/editAssetDetails": typeof assetDefinitions_web_mutations_editAssetDetails;
  "assetDefinitions/web/mutations/generateAssetBarcode": typeof assetDefinitions_web_mutations_generateAssetBarcode;
  "assetDefinitions/web/mutations/performAssetAudit": typeof assetDefinitions_web_mutations_performAssetAudit;
  "assetDefinitions/web/mutations/reactivateAsset": typeof assetDefinitions_web_mutations_reactivateAsset;
  "assetDefinitions/web/mutations/reorderSupplies": typeof assetDefinitions_web_mutations_reorderSupplies;
  "assetDefinitions/web/mutations/retireAsset": typeof assetDefinitions_web_mutations_retireAsset;
  "assetDefinitions/web/mutations/scheduleMaintenance": typeof assetDefinitions_web_mutations_scheduleMaintenance;
  "assetDefinitions/web/mutations/transferAsset": typeof assetDefinitions_web_mutations_transferAsset;
  "assetDefinitions/web/mutations/unassignAssetFromUser": typeof assetDefinitions_web_mutations_unassignAssetFromUser;
  "assetDefinitions/web/mutations/updateAssetStatus": typeof assetDefinitions_web_mutations_updateAssetStatus;
  "assetDefinitions/web/queries/getAssetAlerts": typeof assetDefinitions_web_queries_getAssetAlerts;
  "assetDefinitions/web/queries/getAssetAnalytics": typeof assetDefinitions_web_queries_getAssetAnalytics;
  "assetDefinitions/web/queries/getAssetById": typeof assetDefinitions_web_queries_getAssetById;
  "assetDefinitions/web/queries/getAssetDashboardData": typeof assetDefinitions_web_queries_getAssetDashboardData;
  "assetDefinitions/web/queries/getAssetHistory": typeof assetDefinitions_web_queries_getAssetHistory;
  "assetDefinitions/web/queries/getAssetReports": typeof assetDefinitions_web_queries_getAssetReports;
  "assetDefinitions/web/queries/getAssetUtilization": typeof assetDefinitions_web_queries_getAssetUtilization;
  "assetDefinitions/web/queries/getAssets": typeof assetDefinitions_web_queries_getAssets;
  "assetDefinitions/web/queries/getInventoryLevels": typeof assetDefinitions_web_queries_getInventoryLevels;
  "assetDefinitions/web/queries/getMaintenanceSchedule": typeof assetDefinitions_web_queries_getMaintenanceSchedule;
  "assetDefinitions/web/queries/getManagerProperties": typeof assetDefinitions_web_queries_getManagerProperties;
  assets: typeof assets;
  http: typeof http;
  maintenance: typeof maintenance;
  "maintenanceDefinitions/index": typeof maintenanceDefinitions_index;
  "maintenanceDefinitions/mobile/index": typeof maintenanceDefinitions_mobile_index;
  "maintenanceDefinitions/mobile/mutations/cancelRequest": typeof maintenanceDefinitions_mobile_mutations_cancelRequest;
  "maintenanceDefinitions/mobile/mutations/createRequest": typeof maintenanceDefinitions_mobile_mutations_createRequest;
  "maintenanceDefinitions/mobile/mutations/deleteRequest": typeof maintenanceDefinitions_mobile_mutations_deleteRequest;
  "maintenanceDefinitions/mobile/mutations/index": typeof maintenanceDefinitions_mobile_mutations_index;
  "maintenanceDefinitions/mobile/mutations/tenantConfirmCompletion": typeof maintenanceDefinitions_mobile_mutations_tenantConfirmCompletion;
  "maintenanceDefinitions/mobile/mutations/updateRequest": typeof maintenanceDefinitions_mobile_mutations_updateRequest;
  "maintenanceDefinitions/mobile/queries/getMyCurrentRequests": typeof maintenanceDefinitions_mobile_queries_getMyCurrentRequests;
  "maintenanceDefinitions/mobile/queries/getRequestStatus": typeof maintenanceDefinitions_mobile_queries_getRequestStatus;
  "maintenanceDefinitions/mobile/queries/getRequests": typeof maintenanceDefinitions_mobile_queries_getRequests;
  "maintenanceDefinitions/mobile/queries/getRequestsById": typeof maintenanceDefinitions_mobile_queries_getRequestsById;
  "maintenanceDefinitions/mobile/queries/index": typeof maintenanceDefinitions_mobile_queries_index;
  "maintenanceDefinitions/web/mutations/assignTechnician": typeof maintenanceDefinitions_web_mutations_assignTechnician;
  "maintenanceDefinitions/web/mutations/bulkUpdateStatus": typeof maintenanceDefinitions_web_mutations_bulkUpdateStatus;
  "maintenanceDefinitions/web/mutations/updateMaintenanceCost": typeof maintenanceDefinitions_web_mutations_updateMaintenanceCost;
  "maintenanceDefinitions/web/mutations/updateMaintenanceStatus": typeof maintenanceDefinitions_web_mutations_updateMaintenanceStatus;
  "maintenanceDefinitions/web/queries/getMaintenanceKPIs": typeof maintenanceDefinitions_web_queries_getMaintenanceKPIs;
  "maintenanceDefinitions/web/queries/getMaintenanceRequests": typeof maintenanceDefinitions_web_queries_getMaintenanceRequests;
  "maintenanceDefinitions/web/queries/getMaintenanceTrends": typeof maintenanceDefinitions_web_queries_getMaintenanceTrends;
  "maintenanceDefinitions/web/queries/getMaintenanceUpdates": typeof maintenanceDefinitions_web_queries_getMaintenanceUpdates;
  "maintenanceDefinitions/web/queries/getMaintenanceUpdatesCount": typeof maintenanceDefinitions_web_queries_getMaintenanceUpdatesCount;
  "maintenanceDefinitions/web/queries/getManagerProperties": typeof maintenanceDefinitions_web_queries_getManagerProperties;
  "maintenanceDefinitions/web/queries/getTechnicianWorkload": typeof maintenanceDefinitions_web_queries_getTechnicianWorkload;
  "maintenanceDefinitions/web/queries/getTechnicians": typeof maintenanceDefinitions_web_queries_getTechnicians;
  "maintenanceDefinitions/web/queries/getUnitsByProperty": typeof maintenanceDefinitions_web_queries_getUnitsByProperty;
  noticeboard: typeof noticeboard;
  "noticeboardDefinitions/index": typeof noticeboardDefinitions_index;
  "noticeboardDefinitions/mobile/mutations/acknowledgeNotice": typeof noticeboardDefinitions_mobile_mutations_acknowledgeNotice;
  "noticeboardDefinitions/mobile/mutations/addEventToCalendar": typeof noticeboardDefinitions_mobile_mutations_addEventToCalendar;
  "noticeboardDefinitions/mobile/mutations/sendFeedback": typeof noticeboardDefinitions_mobile_mutations_sendFeedback;
  "noticeboardDefinitions/mobile/mutations/submitPollResponse": typeof noticeboardDefinitions_mobile_mutations_submitPollResponse;
  "noticeboardDefinitions/mobile/queries/getActivePolls": typeof noticeboardDefinitions_mobile_queries_getActivePolls;
  "noticeboardDefinitions/mobile/queries/getCommunityNews": typeof noticeboardDefinitions_mobile_queries_getCommunityNews;
  "noticeboardDefinitions/mobile/queries/getEvents": typeof noticeboardDefinitions_mobile_queries_getEvents;
  "noticeboardDefinitions/mobile/queries/getNoticeById": typeof noticeboardDefinitions_mobile_queries_getNoticeById;
  "noticeboardDefinitions/mobile/queries/getNotices": typeof noticeboardDefinitions_mobile_queries_getNotices;
  "noticeboardDefinitions/web/mutations/acknowledgeNotice": typeof noticeboardDefinitions_web_mutations_acknowledgeNotice;
  "noticeboardDefinitions/web/mutations/createNotice": typeof noticeboardDefinitions_web_mutations_createNotice;
  "noticeboardDefinitions/web/mutations/createPoll": typeof noticeboardDefinitions_web_mutations_createPoll;
  "noticeboardDefinitions/web/mutations/deleteNotice": typeof noticeboardDefinitions_web_mutations_deleteNotice;
  "noticeboardDefinitions/web/mutations/deletePoll": typeof noticeboardDefinitions_web_mutations_deletePoll;
  "noticeboardDefinitions/web/mutations/scheduleNotice": typeof noticeboardDefinitions_web_mutations_scheduleNotice;
  "noticeboardDefinitions/web/mutations/sendNoticeToAll": typeof noticeboardDefinitions_web_mutations_sendNoticeToAll;
  "noticeboardDefinitions/web/mutations/sendNoticeToUnit": typeof noticeboardDefinitions_web_mutations_sendNoticeToUnit;
  "noticeboardDefinitions/web/mutations/submitPollResponse": typeof noticeboardDefinitions_web_mutations_submitPollResponse;
  "noticeboardDefinitions/web/mutations/updateNotice": typeof noticeboardDefinitions_web_mutations_updateNotice;
  "noticeboardDefinitions/web/mutations/updatePoll": typeof noticeboardDefinitions_web_mutations_updatePoll;
  "noticeboardDefinitions/web/queries/getAllUnits": typeof noticeboardDefinitions_web_queries_getAllUnits;
  "noticeboardDefinitions/web/queries/getManagerProperties": typeof noticeboardDefinitions_web_queries_getManagerProperties;
  "noticeboardDefinitions/web/queries/getNoticeAcknowledgments": typeof noticeboardDefinitions_web_queries_getNoticeAcknowledgments;
  "noticeboardDefinitions/web/queries/getNoticeById": typeof noticeboardDefinitions_web_queries_getNoticeById;
  "noticeboardDefinitions/web/queries/getNotices": typeof noticeboardDefinitions_web_queries_getNotices;
  "noticeboardDefinitions/web/queries/getNoticesCount": typeof noticeboardDefinitions_web_queries_getNoticesCount;
  "noticeboardDefinitions/web/queries/getPollResponseCounts": typeof noticeboardDefinitions_web_queries_getPollResponseCounts;
  "noticeboardDefinitions/web/queries/getPollStats": typeof noticeboardDefinitions_web_queries_getPollStats;
  "noticeboardDefinitions/web/queries/getPollWithResponses": typeof noticeboardDefinitions_web_queries_getPollWithResponses;
  "noticeboardDefinitions/web/queries/getPollsByProperty": typeof noticeboardDefinitions_web_queries_getPollsByProperty;
  "noticeboardDefinitions/web/queries/getUnitsByProperty": typeof noticeboardDefinitions_web_queries_getUnitsByProperty;
  property: typeof property;
  "propertyDefinitions/index": typeof propertyDefinitions_index;
  "propertyDefinitions/mobile/index": typeof propertyDefinitions_mobile_index;
  "propertyDefinitions/mobile/queries/getMyProperties": typeof propertyDefinitions_mobile_queries_getMyProperties;
  "propertyDefinitions/mobile/queries/getProperties": typeof propertyDefinitions_mobile_queries_getProperties;
  "propertyDefinitions/mobile/queries/index": typeof propertyDefinitions_mobile_queries_index;
  "propertyDefinitions/web/index": typeof propertyDefinitions_web_index;
  "propertyDefinitions/web/mutations/createProperty": typeof propertyDefinitions_web_mutations_createProperty;
  "propertyDefinitions/web/mutations/index": typeof propertyDefinitions_web_mutations_index;
  "propertyDefinitions/web/queries/getManagerProperties": typeof propertyDefinitions_web_queries_getManagerProperties;
  "propertyDefinitions/web/queries/index": typeof propertyDefinitions_web_queries_index;
  "seeders/assets": typeof seeders_assets;
  "seeders/notice": typeof seeders_notice;
  "seeders/units": typeof seeders_units;
  "seeders/visitorLogs": typeof seeders_visitorLogs;
  "seeders/visitorRequests": typeof seeders_visitorRequests;
  "seeders/watchlist": typeof seeders_watchlist;
  tech: typeof tech;
  "techDefinitions/mobile/index": typeof techDefinitions_mobile_index;
  "techDefinitions/mobile/mutations/addMaintenancePhoto": typeof techDefinitions_mobile_mutations_addMaintenancePhoto;
  "techDefinitions/mobile/mutations/checkinAsset": typeof techDefinitions_mobile_mutations_checkinAsset;
  "techDefinitions/mobile/mutations/checkoutAsset": typeof techDefinitions_mobile_mutations_checkoutAsset;
  "techDefinitions/mobile/mutations/index": typeof techDefinitions_mobile_mutations_index;
  "techDefinitions/mobile/mutations/reportAssetIssue": typeof techDefinitions_mobile_mutations_reportAssetIssue;
  "techDefinitions/mobile/mutations/requestTenantApproval": typeof techDefinitions_mobile_mutations_requestTenantApproval;
  "techDefinitions/mobile/mutations/scheduleAssetMaintenance": typeof techDefinitions_mobile_mutations_scheduleAssetMaintenance;
  "techDefinitions/mobile/mutations/updateMaintenanceCost": typeof techDefinitions_mobile_mutations_updateMaintenanceCost;
  "techDefinitions/mobile/mutations/updateRequestStatus": typeof techDefinitions_mobile_mutations_updateRequestStatus;
  "techDefinitions/mobile/mutations/uploadMaintenancePhoto": typeof techDefinitions_mobile_mutations_uploadMaintenancePhoto;
  "techDefinitions/mobile/queries/getAssetInventory": typeof techDefinitions_mobile_queries_getAssetInventory;
  "techDefinitions/mobile/queries/getAssignedRequests": typeof techDefinitions_mobile_queries_getAssignedRequests;
  "techDefinitions/mobile/queries/getAvailableAssets": typeof techDefinitions_mobile_queries_getAvailableAssets;
  "techDefinitions/mobile/queries/getCheckedOutAssets": typeof techDefinitions_mobile_queries_getCheckedOutAssets;
  "techDefinitions/mobile/queries/getMaintenanceDashboard": typeof techDefinitions_mobile_queries_getMaintenanceDashboard;
  "techDefinitions/mobile/queries/getRequestDetails": typeof techDefinitions_mobile_queries_getRequestDetails;
  "techDefinitions/mobile/queries/index": typeof techDefinitions_mobile_queries_index;
  unit: typeof unit;
  "unitDefinitions/index": typeof unitDefinitions_index;
  "unitDefinitions/mobile/index": typeof unitDefinitions_mobile_index;
  "unitDefinitions/mobile/mutations/assignTenantToUnit": typeof unitDefinitions_mobile_mutations_assignTenantToUnit;
  "unitDefinitions/mobile/mutations/createAndAssignUnit": typeof unitDefinitions_mobile_mutations_createAndAssignUnit;
  "unitDefinitions/mobile/mutations/createUnit": typeof unitDefinitions_mobile_mutations_createUnit;
  "unitDefinitions/mobile/mutations/index": typeof unitDefinitions_mobile_mutations_index;
  "unitDefinitions/mobile/mutations/updateUnit": typeof unitDefinitions_mobile_mutations_updateUnit;
  "unitDefinitions/mobile/queries/getMyUnits": typeof unitDefinitions_mobile_queries_getMyUnits;
  "unitDefinitions/mobile/queries/getUnitDetails": typeof unitDefinitions_mobile_queries_getUnitDetails;
  "unitDefinitions/mobile/queries/getUnitsByProperty": typeof unitDefinitions_mobile_queries_getUnitsByProperty;
  "unitDefinitions/mobile/queries/index": typeof unitDefinitions_mobile_queries_index;
  user: typeof user;
  "userDefinitions/index": typeof userDefinitions_index;
  "userDefinitions/mobile/index": typeof userDefinitions_mobile_index;
  "userDefinitions/mobile/queries/getCurrentUser": typeof userDefinitions_mobile_queries_getCurrentUser;
  "userDefinitions/mobile/queries/index": typeof userDefinitions_mobile_queries_index;
  "userDefinitions/web/index": typeof userDefinitions_web_index;
  "userDefinitions/web/queries/getCurrentUser": typeof userDefinitions_web_queries_getCurrentUser;
  "userDefinitions/web/queries/getUserById": typeof userDefinitions_web_queries_getUserById;
  "userDefinitions/web/queries/getUsers": typeof userDefinitions_web_queries_getUsers;
  visitorLog: typeof visitorLog;
  "visitorLogDefinitions/index": typeof visitorLogDefinitions_index;
  "visitorLogDefinitions/web/mutations/checkInVisitor": typeof visitorLogDefinitions_web_mutations_checkInVisitor;
  "visitorLogDefinitions/web/mutations/checkOutVisitor": typeof visitorLogDefinitions_web_mutations_checkOutVisitor;
  "visitorLogDefinitions/web/mutations/index": typeof visitorLogDefinitions_web_mutations_index;
  "visitorLogDefinitions/web/mutations/markVisitorNoShow": typeof visitorLogDefinitions_web_mutations_markVisitorNoShow;
  "visitorLogDefinitions/web/queries/getVisitorLog": typeof visitorLogDefinitions_web_queries_getVisitorLog;
  "visitorLogDefinitions/web/queries/index": typeof visitorLogDefinitions_web_queries_index;
  visitorRequest: typeof visitorRequest;
  "visitorRequestDefinitions/index": typeof visitorRequestDefinitions_index;
  "visitorRequestDefinitions/web/mutations/approveVisitorRequest": typeof visitorRequestDefinitions_web_mutations_approveVisitorRequest;
  "visitorRequestDefinitions/web/mutations/createVisitorEntry": typeof visitorRequestDefinitions_web_mutations_createVisitorEntry;
  "visitorRequestDefinitions/web/mutations/denyVisitorRequest": typeof visitorRequestDefinitions_web_mutations_denyVisitorRequest;
  "visitorRequestDefinitions/web/mutations/generateVisitorBadge": typeof visitorRequestDefinitions_web_mutations_generateVisitorBadge;
  "visitorRequestDefinitions/web/mutations/index": typeof visitorRequestDefinitions_web_mutations_index;
  "visitorRequestDefinitions/web/queries/exportVisitorReports": typeof visitorRequestDefinitions_web_queries_exportVisitorReports;
  "visitorRequestDefinitions/web/queries/getActiveVisitors": typeof visitorRequestDefinitions_web_queries_getActiveVisitors;
  "visitorRequestDefinitions/web/queries/index": typeof visitorRequestDefinitions_web_queries_index;
  "visitorRequestDefinitions/web/queries/searchVisitorHistory": typeof visitorRequestDefinitions_web_queries_searchVisitorHistory;
  watchList: typeof watchList;
  "watchListDefinitions/index": typeof watchListDefinitions_index;
  "watchListDefinitions/web/mutations/manageWatchlist": typeof watchListDefinitions_web_mutations_manageWatchlist;
  webhook: typeof webhook;
  "webhookDefinitions/handleUserCreated": typeof webhookDefinitions_handleUserCreated;
  "webhookDefinitions/handleUserDeleted": typeof webhookDefinitions_handleUserDeleted;
  "webhookDefinitions/handleUserUpdated": typeof webhookDefinitions_handleUserUpdated;
  "webhookDefinitions/index": typeof webhookDefinitions_index;
  "webhookDefinitions/verifyWebhook": typeof webhookDefinitions_verifyWebhook;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
